export {default as Login} from "./AuthPages/Login/Login"
export {default as Register} from "./AuthPages/Register/Register"
export {default as HomePage} from "./HomePage/HomePage"
export {default as DashboardPage} from "./DashboardPage/DashboardPage"
export {default as Aboutus} from "./AboutUs/Aboutus"
export {default as Contributer} from "./Contributers/Contributer"